---
- name: Configure iptables to control SSH and ping based on the host list
  hosts: demo
  become: yes
  vars:
    allowed_addresses:
      - 192.168.0.10
      - 192.168.123.10

  tasks:
    # Flush all existing iptables rules to start with a clean state
    - name: Flush all existing iptables rules
      ansible.builtin.shell: "iptables -F"

    # Allow all incoming traffic from the list of allowed addresses
    - name: Allow all incoming traffic from allowed addresses
      ansible.builtin.shell: "iptables -A INPUT -s {{ item }} -j ACCEPT"
      loop: "{{ allowed_addresses }}"

    # Allow established and related connections using shell command
    - name: Allow established and related connections
      ansible.builtin.shell: "iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT"

    # Allow traffic from specific IP addresses (instead of loopback interface)
    - name: Allow traffic from specific IP addresses
      ansible.builtin.shell: "iptables -A INPUT -s {{ item }} -j ACCEPT"
      loop: "{{ allowed_addresses }}"

    # Drop all other incoming traffic to enhance security
    - name: Drop all other incoming traffic
      ansible.builtin.shell: "iptables -P INPUT DROP"

    # Ensure iptables-persistent is installed to make iptables rules persistent across reboots
    - name: Ensure iptables-persistent is installed
      ansible.builtin.apt:
        name: iptables-persistent
        state: present

    # Save the current iptables rules to the persistent rules file
    - name: Save the rules to iptables
      ansible.builtin.shell: "/sbin/iptables-save > /etc/iptables/rules.v4"
...
