---
- name: Configure iptables for specific SSH access
  hosts: server
  become: yes  # Required to modify iptables
  tasks:
    - name: Flush existing iptables rules
      iptables:
        flush: yes

    - name: Set default DROP policy for INPUT chain
      iptables:
        chain: INPUT
        policy: DROP

    - name: Set default DROP policy for FORWARD chain
      iptables:
        chain: FORWARD
        policy: DROP

    - name: Set default ACCEPT policy for OUTPUT chain
      iptables:
        chain: OUTPUT
        policy: ACCEPT

    - name: Allow SSH from specific IP
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.0.117
        jump: ACCEPT

    - name: Save iptables rules
      command: /sbin/service iptables save

...
