---
- name: Configure iptables to control SSH and ping based on the host list
  hosts: all
  become: yes
  vars:
    allow_ansible_control_node:
      - 192.168.0.10
    other_allowed_connections:
      - 192.168.123.10

  tasks:
    - name: Allow all incoming traffic from ansible control node
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ item }}"
        jump: ACCEPT
        comment: "Allow incoming traffic from ansible control node"
      loop: "{{ allow_ansible_control_node }}"

    - name: Allow access for other specific IP addresses
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ item }}"
        jump: ACCEPT
        comment: "Allow incoming traffic from secure IP lists"
      loop: "{{ other_allowed_connections }}"

    - name: Drop all other incoming traffic
      ansible.builtin.iptables:
        chain: INPUT
        jump: DROP
        comment: "Drop all access"

    - name: Save the rules to iptables
      ansible.builtin.shell: "/sbin/iptables-save > /etc/iptables/rules.v4"
...



