---
- name: Configure iptables to control SSH and ping based on the host list
  hosts: all
  become: yes
  vars:
    allowed_ips:
      - 192.168.123.10

  tasks:
    - name: Allow all incoming traffic from listed addresses
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ item }}"
        jump: ACCEPT
        comment: "Allow all incoming traffic from listed addresses"
      loop: "{{ allowed_ips }}"

    - name: Save the rules to iptables
      ansible.builtin.shell: "/sbin/iptables-save > /etc/iptables/rules.v4"
...
